-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sha256_top_sha256_transform_Pipeline_VITIS_LOOP_33_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    b : IN STD_LOGIC_VECTOR (31 downto 0);
    c : IN STD_LOGIC_VECTOR (31 downto 0);
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    e : IN STD_LOGIC_VECTOR (31 downto 0);
    f : IN STD_LOGIC_VECTOR (31 downto 0);
    g : IN STD_LOGIC_VECTOR (31 downto 0);
    h : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_s : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    or_ln16_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    m_16_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_17_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_18_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_19_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_20_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_21_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_22_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_23_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_24_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_25_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_26_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_27_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_28_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_29_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_30_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_31_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_32_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_33_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_34_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_35_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_36_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_37_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_38_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_39_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_40_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_41_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_42_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_43_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_44_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_45_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_46_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_47_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_48_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_49_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_50_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_51_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_52_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_53_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_54_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_55_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_56_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_57_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_58_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_59_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_60_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_61_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_62_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    m_63_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    a_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    a_3_out_ap_vld : OUT STD_LOGIC;
    b_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_3_out_ap_vld : OUT STD_LOGIC;
    c_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_3_out_ap_vld : OUT STD_LOGIC;
    d_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    d_1_out_ap_vld : OUT STD_LOGIC;
    e_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    e_3_out_ap_vld : OUT STD_LOGIC;
    f_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    f_3_out_ap_vld : OUT STD_LOGIC;
    g_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    g_3_out_ap_vld : OUT STD_LOGIC;
    h_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    h_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of sha256_top_sha256_transform_Pipeline_VITIS_LOOP_33_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln33_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal k_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal k_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln33_reg_1625 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_4_fu_968_p131 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_reg_1634 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln33_fu_959_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal h_1_fu_362 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal d_1_fu_366 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i_fu_370 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln33_fu_953_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal h_2_fu_374 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal g_1_fu_378 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal f_1_fu_382 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal e_2_fu_1434_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal d_2_fu_386 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal c_1_fu_390 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_1_fu_394 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal a_2_fu_1506_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal k_ce0_local : STD_LOGIC;
    signal tmp_4_fu_968_p129 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_968_p130 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln35_fu_1277_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln1_fu_1267_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln35_1_fu_1291_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln35_1_fu_1281_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal xor_ln35_fu_1309_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln35_2_fu_1305_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal lshr_ln35_2_fu_1295_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln35_1_fu_1337_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln35_fu_1331_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln35_1_fu_1323_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln35_2_fu_1343_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln35_2_fu_1357_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1_fu_1315_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln35_1_fu_1351_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_1_fu_1375_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln35_3_fu_1363_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_2_fu_1380_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_fu_1369_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal t1_fu_1386_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln44_fu_1440_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln36_fu_1402_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln2_fu_1392_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln36_1_fu_1416_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln36_1_fu_1406_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal and_ln44_fu_1446_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln44_1_fu_1452_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln36_2_fu_1430_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal lshr_ln36_2_fu_1420_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln44_1_fu_1466_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln44_2_fu_1480_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln44_2_fu_1488_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln2_fu_1458_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln44_3_fu_1494_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_fu_1500_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln44_1_fu_1474_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_4_fu_968_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p21 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p23 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p25 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p29 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p31 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p35 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p37 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p39 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p41 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p43 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p45 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p47 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p49 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p51 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p53 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p55 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p57 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p59 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p61 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p63 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p65 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p67 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p69 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p71 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p73 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p75 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p77 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p79 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p81 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p83 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p85 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p87 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p89 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p91 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p93 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p95 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p97 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p99 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p101 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p103 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p105 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p107 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p109 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p111 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p113 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p115 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p117 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p119 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p121 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p123 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p125 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_968_p127 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component sha256_top_sparsemux_129_6_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (5 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (5 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (5 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (5 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (5 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (5 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (5 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (5 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (5 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (5 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (5 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (5 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (5 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (5 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (5 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (5 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (5 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (5 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (5 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (5 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (5 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (5 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (5 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (5 downto 0);
        din31_WIDTH : INTEGER;
        CASE32 : STD_LOGIC_VECTOR (5 downto 0);
        din32_WIDTH : INTEGER;
        CASE33 : STD_LOGIC_VECTOR (5 downto 0);
        din33_WIDTH : INTEGER;
        CASE34 : STD_LOGIC_VECTOR (5 downto 0);
        din34_WIDTH : INTEGER;
        CASE35 : STD_LOGIC_VECTOR (5 downto 0);
        din35_WIDTH : INTEGER;
        CASE36 : STD_LOGIC_VECTOR (5 downto 0);
        din36_WIDTH : INTEGER;
        CASE37 : STD_LOGIC_VECTOR (5 downto 0);
        din37_WIDTH : INTEGER;
        CASE38 : STD_LOGIC_VECTOR (5 downto 0);
        din38_WIDTH : INTEGER;
        CASE39 : STD_LOGIC_VECTOR (5 downto 0);
        din39_WIDTH : INTEGER;
        CASE40 : STD_LOGIC_VECTOR (5 downto 0);
        din40_WIDTH : INTEGER;
        CASE41 : STD_LOGIC_VECTOR (5 downto 0);
        din41_WIDTH : INTEGER;
        CASE42 : STD_LOGIC_VECTOR (5 downto 0);
        din42_WIDTH : INTEGER;
        CASE43 : STD_LOGIC_VECTOR (5 downto 0);
        din43_WIDTH : INTEGER;
        CASE44 : STD_LOGIC_VECTOR (5 downto 0);
        din44_WIDTH : INTEGER;
        CASE45 : STD_LOGIC_VECTOR (5 downto 0);
        din45_WIDTH : INTEGER;
        CASE46 : STD_LOGIC_VECTOR (5 downto 0);
        din46_WIDTH : INTEGER;
        CASE47 : STD_LOGIC_VECTOR (5 downto 0);
        din47_WIDTH : INTEGER;
        CASE48 : STD_LOGIC_VECTOR (5 downto 0);
        din48_WIDTH : INTEGER;
        CASE49 : STD_LOGIC_VECTOR (5 downto 0);
        din49_WIDTH : INTEGER;
        CASE50 : STD_LOGIC_VECTOR (5 downto 0);
        din50_WIDTH : INTEGER;
        CASE51 : STD_LOGIC_VECTOR (5 downto 0);
        din51_WIDTH : INTEGER;
        CASE52 : STD_LOGIC_VECTOR (5 downto 0);
        din52_WIDTH : INTEGER;
        CASE53 : STD_LOGIC_VECTOR (5 downto 0);
        din53_WIDTH : INTEGER;
        CASE54 : STD_LOGIC_VECTOR (5 downto 0);
        din54_WIDTH : INTEGER;
        CASE55 : STD_LOGIC_VECTOR (5 downto 0);
        din55_WIDTH : INTEGER;
        CASE56 : STD_LOGIC_VECTOR (5 downto 0);
        din56_WIDTH : INTEGER;
        CASE57 : STD_LOGIC_VECTOR (5 downto 0);
        din57_WIDTH : INTEGER;
        CASE58 : STD_LOGIC_VECTOR (5 downto 0);
        din58_WIDTH : INTEGER;
        CASE59 : STD_LOGIC_VECTOR (5 downto 0);
        din59_WIDTH : INTEGER;
        CASE60 : STD_LOGIC_VECTOR (5 downto 0);
        din60_WIDTH : INTEGER;
        CASE61 : STD_LOGIC_VECTOR (5 downto 0);
        din61_WIDTH : INTEGER;
        CASE62 : STD_LOGIC_VECTOR (5 downto 0);
        din62_WIDTH : INTEGER;
        CASE63 : STD_LOGIC_VECTOR (5 downto 0);
        din63_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (31 downto 0);
        din17 : IN STD_LOGIC_VECTOR (31 downto 0);
        din18 : IN STD_LOGIC_VECTOR (31 downto 0);
        din19 : IN STD_LOGIC_VECTOR (31 downto 0);
        din20 : IN STD_LOGIC_VECTOR (31 downto 0);
        din21 : IN STD_LOGIC_VECTOR (31 downto 0);
        din22 : IN STD_LOGIC_VECTOR (31 downto 0);
        din23 : IN STD_LOGIC_VECTOR (31 downto 0);
        din24 : IN STD_LOGIC_VECTOR (31 downto 0);
        din25 : IN STD_LOGIC_VECTOR (31 downto 0);
        din26 : IN STD_LOGIC_VECTOR (31 downto 0);
        din27 : IN STD_LOGIC_VECTOR (31 downto 0);
        din28 : IN STD_LOGIC_VECTOR (31 downto 0);
        din29 : IN STD_LOGIC_VECTOR (31 downto 0);
        din30 : IN STD_LOGIC_VECTOR (31 downto 0);
        din31 : IN STD_LOGIC_VECTOR (31 downto 0);
        din32 : IN STD_LOGIC_VECTOR (31 downto 0);
        din33 : IN STD_LOGIC_VECTOR (31 downto 0);
        din34 : IN STD_LOGIC_VECTOR (31 downto 0);
        din35 : IN STD_LOGIC_VECTOR (31 downto 0);
        din36 : IN STD_LOGIC_VECTOR (31 downto 0);
        din37 : IN STD_LOGIC_VECTOR (31 downto 0);
        din38 : IN STD_LOGIC_VECTOR (31 downto 0);
        din39 : IN STD_LOGIC_VECTOR (31 downto 0);
        din40 : IN STD_LOGIC_VECTOR (31 downto 0);
        din41 : IN STD_LOGIC_VECTOR (31 downto 0);
        din42 : IN STD_LOGIC_VECTOR (31 downto 0);
        din43 : IN STD_LOGIC_VECTOR (31 downto 0);
        din44 : IN STD_LOGIC_VECTOR (31 downto 0);
        din45 : IN STD_LOGIC_VECTOR (31 downto 0);
        din46 : IN STD_LOGIC_VECTOR (31 downto 0);
        din47 : IN STD_LOGIC_VECTOR (31 downto 0);
        din48 : IN STD_LOGIC_VECTOR (31 downto 0);
        din49 : IN STD_LOGIC_VECTOR (31 downto 0);
        din50 : IN STD_LOGIC_VECTOR (31 downto 0);
        din51 : IN STD_LOGIC_VECTOR (31 downto 0);
        din52 : IN STD_LOGIC_VECTOR (31 downto 0);
        din53 : IN STD_LOGIC_VECTOR (31 downto 0);
        din54 : IN STD_LOGIC_VECTOR (31 downto 0);
        din55 : IN STD_LOGIC_VECTOR (31 downto 0);
        din56 : IN STD_LOGIC_VECTOR (31 downto 0);
        din57 : IN STD_LOGIC_VECTOR (31 downto 0);
        din58 : IN STD_LOGIC_VECTOR (31 downto 0);
        din59 : IN STD_LOGIC_VECTOR (31 downto 0);
        din60 : IN STD_LOGIC_VECTOR (31 downto 0);
        din61 : IN STD_LOGIC_VECTOR (31 downto 0);
        din62 : IN STD_LOGIC_VECTOR (31 downto 0);
        din63 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sha256_top_sha256_transform_Pipeline_VITIS_LOOP_33_3_k_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sha256_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    k_U : component sha256_top_sha256_transform_Pipeline_VITIS_LOOP_33_3_k_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_address0,
        ce0 => k_ce0_local,
        q0 => k_q0);

    sparsemux_129_6_32_1_1_U71 : component sha256_top_sparsemux_129_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "000001",
        din1_WIDTH => 32,
        CASE2 => "000010",
        din2_WIDTH => 32,
        CASE3 => "000011",
        din3_WIDTH => 32,
        CASE4 => "000100",
        din4_WIDTH => 32,
        CASE5 => "000101",
        din5_WIDTH => 32,
        CASE6 => "000110",
        din6_WIDTH => 32,
        CASE7 => "000111",
        din7_WIDTH => 32,
        CASE8 => "001000",
        din8_WIDTH => 32,
        CASE9 => "001001",
        din9_WIDTH => 32,
        CASE10 => "001010",
        din10_WIDTH => 32,
        CASE11 => "001011",
        din11_WIDTH => 32,
        CASE12 => "001100",
        din12_WIDTH => 32,
        CASE13 => "001101",
        din13_WIDTH => 32,
        CASE14 => "001110",
        din14_WIDTH => 32,
        CASE15 => "001111",
        din15_WIDTH => 32,
        CASE16 => "010000",
        din16_WIDTH => 32,
        CASE17 => "010001",
        din17_WIDTH => 32,
        CASE18 => "010010",
        din18_WIDTH => 32,
        CASE19 => "010011",
        din19_WIDTH => 32,
        CASE20 => "010100",
        din20_WIDTH => 32,
        CASE21 => "010101",
        din21_WIDTH => 32,
        CASE22 => "010110",
        din22_WIDTH => 32,
        CASE23 => "010111",
        din23_WIDTH => 32,
        CASE24 => "011000",
        din24_WIDTH => 32,
        CASE25 => "011001",
        din25_WIDTH => 32,
        CASE26 => "011010",
        din26_WIDTH => 32,
        CASE27 => "011011",
        din27_WIDTH => 32,
        CASE28 => "011100",
        din28_WIDTH => 32,
        CASE29 => "011101",
        din29_WIDTH => 32,
        CASE30 => "011110",
        din30_WIDTH => 32,
        CASE31 => "011111",
        din31_WIDTH => 32,
        CASE32 => "100000",
        din32_WIDTH => 32,
        CASE33 => "100001",
        din33_WIDTH => 32,
        CASE34 => "100010",
        din34_WIDTH => 32,
        CASE35 => "100011",
        din35_WIDTH => 32,
        CASE36 => "100100",
        din36_WIDTH => 32,
        CASE37 => "100101",
        din37_WIDTH => 32,
        CASE38 => "100110",
        din38_WIDTH => 32,
        CASE39 => "100111",
        din39_WIDTH => 32,
        CASE40 => "101000",
        din40_WIDTH => 32,
        CASE41 => "101001",
        din41_WIDTH => 32,
        CASE42 => "101010",
        din42_WIDTH => 32,
        CASE43 => "101011",
        din43_WIDTH => 32,
        CASE44 => "101100",
        din44_WIDTH => 32,
        CASE45 => "101101",
        din45_WIDTH => 32,
        CASE46 => "101110",
        din46_WIDTH => 32,
        CASE47 => "101111",
        din47_WIDTH => 32,
        CASE48 => "110000",
        din48_WIDTH => 32,
        CASE49 => "110001",
        din49_WIDTH => 32,
        CASE50 => "110010",
        din50_WIDTH => 32,
        CASE51 => "110011",
        din51_WIDTH => 32,
        CASE52 => "110100",
        din52_WIDTH => 32,
        CASE53 => "110101",
        din53_WIDTH => 32,
        CASE54 => "110110",
        din54_WIDTH => 32,
        CASE55 => "110111",
        din55_WIDTH => 32,
        CASE56 => "111000",
        din56_WIDTH => 32,
        CASE57 => "111001",
        din57_WIDTH => 32,
        CASE58 => "111010",
        din58_WIDTH => 32,
        CASE59 => "111011",
        din59_WIDTH => 32,
        CASE60 => "111100",
        din60_WIDTH => 32,
        CASE61 => "111101",
        din61_WIDTH => 32,
        CASE62 => "111110",
        din62_WIDTH => 32,
        CASE63 => "111111",
        din63_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => or_ln16_2,
        din1 => or_ln16_5,
        din2 => or_ln16_8,
        din3 => or_ln16_s,
        din4 => or_ln16_1,
        din5 => or_ln16_3,
        din6 => or_ln16_4,
        din7 => or_ln16_6,
        din8 => or_ln16_7,
        din9 => or_ln16_9,
        din10 => or_ln16_10,
        din11 => or_ln16_11,
        din12 => or_ln16_12,
        din13 => or_ln16_13,
        din14 => or_ln16_14,
        din15 => or_ln16_15,
        din16 => m_16_load_reload,
        din17 => m_17_load_reload,
        din18 => m_18_load_reload,
        din19 => m_19_load_reload,
        din20 => m_20_load_reload,
        din21 => m_21_load_reload,
        din22 => m_22_load_reload,
        din23 => m_23_load_reload,
        din24 => m_24_load_reload,
        din25 => m_25_load_reload,
        din26 => m_26_load_reload,
        din27 => m_27_load_reload,
        din28 => m_28_load_reload,
        din29 => m_29_load_reload,
        din30 => m_30_load_reload,
        din31 => m_31_load_reload,
        din32 => m_32_load_reload,
        din33 => m_33_load_reload,
        din34 => m_34_load_reload,
        din35 => m_35_load_reload,
        din36 => m_36_load_reload,
        din37 => m_37_load_reload,
        din38 => m_38_load_reload,
        din39 => m_39_load_reload,
        din40 => m_40_load_reload,
        din41 => m_41_load_reload,
        din42 => m_42_load_reload,
        din43 => m_43_load_reload,
        din44 => m_44_load_reload,
        din45 => m_45_load_reload,
        din46 => m_46_load_reload,
        din47 => m_47_load_reload,
        din48 => m_48_load_reload,
        din49 => m_49_load_reload,
        din50 => m_50_load_reload,
        din51 => m_51_load_reload,
        din52 => m_52_load_reload,
        din53 => m_53_load_reload,
        din54 => m_54_load_reload,
        din55 => m_55_load_reload,
        din56 => m_56_load_reload,
        din57 => m_57_load_reload,
        din58 => m_58_load_reload,
        din59 => m_59_load_reload,
        din60 => m_60_load_reload,
        din61 => m_61_load_reload,
        din62 => m_62_load_reload,
        din63 => m_63_load_reload,
        def => tmp_4_fu_968_p129,
        sel => tmp_4_fu_968_p130,
        dout => tmp_4_fu_968_p131);

    flow_control_loop_pipe_sequential_init_U : component sha256_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    b_1_fu_394_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    b_1_fu_394 <= a;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_0))) then 
                    b_1_fu_394 <= a_2_fu_1506_p2;
                end if;
            end if; 
        end if;
    end process;

    c_1_fu_390_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_1_fu_390 <= b;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_0))) then 
                    c_1_fu_390 <= b_1_fu_394;
                end if;
            end if; 
        end if;
    end process;

    d_1_fu_366_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    d_1_fu_366 <= d;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_0))) then 
                    d_1_fu_366 <= d_2_fu_386;
                end if;
            end if; 
        end if;
    end process;

    d_2_fu_386_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    d_2_fu_386 <= c;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_0))) then 
                    d_2_fu_386 <= c_1_fu_390;
                end if;
            end if; 
        end if;
    end process;

    f_1_fu_382_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    f_1_fu_382 <= e;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_0))) then 
                    f_1_fu_382 <= e_2_fu_1434_p2;
                end if;
            end if; 
        end if;
    end process;

    g_1_fu_378_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    g_1_fu_378 <= f;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_0))) then 
                    g_1_fu_378 <= f_1_fu_382;
                end if;
            end if; 
        end if;
    end process;

    h_1_fu_362_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    h_1_fu_362 <= h;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_0))) then 
                    h_1_fu_362 <= h_2_fu_374;
                end if;
            end if; 
        end if;
    end process;

    h_2_fu_374_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    h_2_fu_374 <= g;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_0))) then 
                    h_2_fu_374 <= g_1_fu_378;
                end if;
            end if; 
        end if;
    end process;

    i_fu_370_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln33_fu_947_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_370 <= add_ln33_fu_953_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_370 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln33_reg_1625 <= icmp_ln33_fu_947_p2;
                tmp_4_reg_1634 <= tmp_4_fu_968_p131;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_2_fu_1506_p2 <= std_logic_vector(unsigned(add_ln44_fu_1500_p2) + unsigned(xor_ln44_1_fu_1474_p2));
    a_3_out <= b_1_fu_394;

    a_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln33_reg_1625, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_1))) then 
            a_3_out_ap_vld <= ap_const_logic_1;
        else 
            a_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln33_fu_953_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv7_1));
    add_ln35_1_fu_1375_p2 <= std_logic_vector(unsigned(tmp_4_reg_1634) + unsigned(xor_ln35_1_fu_1351_p2));
    add_ln35_2_fu_1380_p2 <= std_logic_vector(unsigned(add_ln35_1_fu_1375_p2) + unsigned(xor_ln35_3_fu_1363_p2));
    add_ln35_fu_1369_p2 <= std_logic_vector(unsigned(k_q0) + unsigned(h_1_fu_362));
    add_ln44_fu_1500_p2 <= std_logic_vector(unsigned(t1_fu_1386_p2) + unsigned(xor_ln44_3_fu_1494_p2));
    and_ln35_1_fu_1337_p2 <= (xor_ln35_fu_1309_p2 and h_2_fu_374);
    and_ln35_fu_1331_p2 <= (g_1_fu_378 and f_1_fu_382);
    and_ln44_1_fu_1452_p2 <= (d_2_fu_386 and c_1_fu_390);
    and_ln44_fu_1446_p2 <= (xor_ln44_fu_1440_p2 and b_1_fu_394);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln33_fu_947_p2)
    begin
        if (((icmp_ln33_fu_947_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_370)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_370;
        end if; 
    end process;

    b_3_out <= c_1_fu_390;

    b_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln33_reg_1625, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_1))) then 
            b_3_out_ap_vld <= ap_const_logic_1;
        else 
            b_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    c_3_out <= d_2_fu_386;

    c_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln33_reg_1625, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_1))) then 
            c_3_out_ap_vld <= ap_const_logic_1;
        else 
            c_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    d_1_out <= d_1_fu_366;

    d_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln33_reg_1625, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_1))) then 
            d_1_out_ap_vld <= ap_const_logic_1;
        else 
            d_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    e_2_fu_1434_p2 <= std_logic_vector(unsigned(t1_fu_1386_p2) + unsigned(d_1_fu_366));
    e_3_out <= f_1_fu_382;

    e_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln33_reg_1625, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_1))) then 
            e_3_out_ap_vld <= ap_const_logic_1;
        else 
            e_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    f_3_out <= g_1_fu_378;

    f_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln33_reg_1625, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_1))) then 
            f_3_out_ap_vld <= ap_const_logic_1;
        else 
            f_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    g_3_out <= h_2_fu_374;

    g_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln33_reg_1625, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_1))) then 
            g_3_out_ap_vld <= ap_const_logic_1;
        else 
            g_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    h_1_out <= h_1_fu_362;

    h_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln33_reg_1625, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln33_reg_1625 = ap_const_lv1_1))) then 
            h_1_out_ap_vld <= ap_const_logic_1;
        else 
            h_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln33_fu_947_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv7_40) else "0";
    k_address0 <= zext_ln33_fu_959_p1(6 - 1 downto 0);

    k_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            k_ce0_local <= ap_const_logic_1;
        else 
            k_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln1_fu_1267_p4 <= f_1_fu_382(31 downto 6);
    lshr_ln2_fu_1392_p4 <= b_1_fu_394(31 downto 2);
    lshr_ln35_1_fu_1281_p4 <= f_1_fu_382(31 downto 11);
    lshr_ln35_2_fu_1295_p4 <= f_1_fu_382(31 downto 25);
    lshr_ln36_1_fu_1406_p4 <= b_1_fu_394(31 downto 13);
    lshr_ln36_2_fu_1420_p4 <= b_1_fu_394(31 downto 22);
    or_ln1_fu_1315_p3 <= (trunc_ln35_fu_1277_p1 & lshr_ln1_fu_1267_p4);
    or_ln2_fu_1458_p3 <= (trunc_ln36_fu_1402_p1 & lshr_ln2_fu_1392_p4);
    or_ln35_1_fu_1323_p3 <= (trunc_ln35_1_fu_1291_p1 & lshr_ln35_1_fu_1281_p4);
    or_ln35_2_fu_1343_p3 <= (trunc_ln35_2_fu_1305_p1 & lshr_ln35_2_fu_1295_p4);
    or_ln44_1_fu_1466_p3 <= (trunc_ln36_1_fu_1416_p1 & lshr_ln36_1_fu_1406_p4);
    or_ln44_2_fu_1480_p3 <= (trunc_ln36_2_fu_1430_p1 & lshr_ln36_2_fu_1420_p4);
    t1_fu_1386_p2 <= std_logic_vector(unsigned(add_ln35_2_fu_1380_p2) + unsigned(add_ln35_fu_1369_p2));
    tmp_4_fu_968_p129 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_4_fu_968_p130 <= ap_sig_allocacmp_i_1(6 - 1 downto 0);
    trunc_ln35_1_fu_1291_p1 <= f_1_fu_382(11 - 1 downto 0);
    trunc_ln35_2_fu_1305_p1 <= f_1_fu_382(25 - 1 downto 0);
    trunc_ln35_fu_1277_p1 <= f_1_fu_382(6 - 1 downto 0);
    trunc_ln36_1_fu_1416_p1 <= b_1_fu_394(13 - 1 downto 0);
    trunc_ln36_2_fu_1430_p1 <= b_1_fu_394(22 - 1 downto 0);
    trunc_ln36_fu_1402_p1 <= b_1_fu_394(2 - 1 downto 0);
    xor_ln35_1_fu_1351_p2 <= (and_ln35_fu_1331_p2 xor and_ln35_1_fu_1337_p2);
    xor_ln35_2_fu_1357_p2 <= (or_ln35_2_fu_1343_p3 xor or_ln35_1_fu_1323_p3);
    xor_ln35_3_fu_1363_p2 <= (xor_ln35_2_fu_1357_p2 xor or_ln1_fu_1315_p3);
    xor_ln35_fu_1309_p2 <= (f_1_fu_382 xor ap_const_lv32_FFFFFFFF);
    xor_ln44_1_fu_1474_p2 <= (and_ln44_fu_1446_p2 xor and_ln44_1_fu_1452_p2);
    xor_ln44_2_fu_1488_p2 <= (or_ln44_2_fu_1480_p3 xor or_ln44_1_fu_1466_p3);
    xor_ln44_3_fu_1494_p2 <= (xor_ln44_2_fu_1488_p2 xor or_ln2_fu_1458_p3);
    xor_ln44_fu_1440_p2 <= (d_2_fu_386 xor c_1_fu_390);
    zext_ln33_fu_959_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),64));
end behav;
