// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sha256_top_sha256_final_Pipeline_VITIS_LOOP_106_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln97,
        in_data_57,
        in_data_57_ap_vld,
        in_data_63,
        in_data_63_ap_vld,
        in_data_62,
        in_data_62_ap_vld,
        in_data_61,
        in_data_61_ap_vld,
        in_data_60,
        in_data_60_ap_vld,
        in_data_59,
        in_data_59_ap_vld,
        in_data_58,
        in_data_58_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] zext_ln97;
output  [7:0] in_data_57;
output   in_data_57_ap_vld;
output  [7:0] in_data_63;
output   in_data_63_ap_vld;
output  [7:0] in_data_62;
output   in_data_62_ap_vld;
output  [7:0] in_data_61;
output   in_data_61_ap_vld;
output  [7:0] in_data_60;
output   in_data_60_ap_vld;
output  [7:0] in_data_59;
output   in_data_59_ap_vld;
output  [7:0] in_data_58;
output   in_data_58_ap_vld;

reg ap_idle;
reg in_data_57_ap_vld;
reg in_data_63_ap_vld;
reg in_data_62_ap_vld;
reg in_data_61_ap_vld;
reg in_data_60_ap_vld;
reg in_data_59_ap_vld;
reg in_data_58_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln106_fu_140_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [6:0] i_7_in_fu_52;
wire   [6:0] zext_ln97_cast_cast_fu_122_p1;
wire   [6:0] i_fu_134_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_7_in_load;
wire   [3:0] trunc_ln98_fu_146_p1;
wire  signed [5:0] zext_ln97_cast_fu_118_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_7_in_fu_52 = 7'd0;
#0 ap_done_reg = 1'b0;
end

sha256_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln106_fu_140_p2 == 1'd0)) begin
            i_7_in_fu_52 <= i_fu_134_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_7_in_fu_52 <= zext_ln97_cast_cast_fu_122_p1;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln106_fu_140_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_7_in_load = zext_ln97_cast_cast_fu_122_p1;
    end else begin
        ap_sig_allocacmp_i_7_in_load = i_7_in_fu_52;
    end
end

always @ (*) begin
    if (((trunc_ln98_fu_146_p1 == 4'd9) & (icmp_ln106_fu_140_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_57_ap_vld = 1'b1;
    end else begin
        in_data_57_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln98_fu_146_p1 == 4'd10) & (icmp_ln106_fu_140_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_58_ap_vld = 1'b1;
    end else begin
        in_data_58_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln98_fu_146_p1 == 4'd11) & (icmp_ln106_fu_140_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_59_ap_vld = 1'b1;
    end else begin
        in_data_59_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln98_fu_146_p1 == 4'd12) & (icmp_ln106_fu_140_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_60_ap_vld = 1'b1;
    end else begin
        in_data_60_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln98_fu_146_p1 == 4'd13) & (icmp_ln106_fu_140_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_61_ap_vld = 1'b1;
    end else begin
        in_data_61_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln98_fu_146_p1 == 4'd14) & (icmp_ln106_fu_140_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_62_ap_vld = 1'b1;
    end else begin
        in_data_62_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln98_fu_146_p1 == 4'd14) & ~(trunc_ln98_fu_146_p1 == 4'd13) & ~(trunc_ln98_fu_146_p1 == 4'd12) & ~(trunc_ln98_fu_146_p1 == 4'd11) & ~(trunc_ln98_fu_146_p1 == 4'd10) & ~(trunc_ln98_fu_146_p1 == 4'd9) & (icmp_ln106_fu_140_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_data_63_ap_vld = 1'b1;
    end else begin
        in_data_63_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_fu_134_p2 = (ap_sig_allocacmp_i_7_in_load + 7'd1);

assign icmp_ln106_fu_140_p2 = ((i_fu_134_p2 == 7'd64) ? 1'b1 : 1'b0);

assign in_data_57 = 8'd0;

assign in_data_58 = 8'd0;

assign in_data_59 = 8'd0;

assign in_data_60 = 8'd0;

assign in_data_61 = 8'd0;

assign in_data_62 = 8'd0;

assign in_data_63 = 8'd0;

assign trunc_ln98_fu_146_p1 = i_fu_134_p2[3:0];

assign zext_ln97_cast_cast_fu_122_p1 = $unsigned(zext_ln97_cast_fu_118_p1);

assign zext_ln97_cast_fu_118_p1 = $signed(zext_ln97);

endmodule //sha256_top_sha256_final_Pipeline_VITIS_LOOP_106_2
