// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sha256_top_sha256_transform_Pipeline_VITIS_LOOP_33_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        or_ln16_2,
        or_ln16_5,
        or_ln16_8,
        or_ln16_s,
        or_ln16_1,
        or_ln16_3,
        or_ln16_4,
        or_ln16_6,
        or_ln16_7,
        or_ln16_9,
        or_ln16_10,
        or_ln16_11,
        or_ln16_12,
        or_ln16_13,
        or_ln16_14,
        or_ln16_15,
        m_16_load_reload,
        m_17_load_reload,
        m_18_load_reload,
        m_19_load_reload,
        m_20_load_reload,
        m_21_load_reload,
        m_22_load_reload,
        m_23_load_reload,
        m_24_load_reload,
        m_25_load_reload,
        m_26_load_reload,
        m_27_load_reload,
        m_28_load_reload,
        m_29_load_reload,
        m_30_load_reload,
        m_31_load_reload,
        m_32_load_reload,
        m_33_load_reload,
        m_34_load_reload,
        m_35_load_reload,
        m_36_load_reload,
        m_37_load_reload,
        m_38_load_reload,
        m_39_load_reload,
        m_40_load_reload,
        m_41_load_reload,
        m_42_load_reload,
        m_43_load_reload,
        m_44_load_reload,
        m_45_load_reload,
        m_46_load_reload,
        m_47_load_reload,
        m_48_load_reload,
        m_49_load_reload,
        m_50_load_reload,
        m_51_load_reload,
        m_52_load_reload,
        m_53_load_reload,
        m_54_load_reload,
        m_55_load_reload,
        m_56_load_reload,
        m_57_load_reload,
        m_58_load_reload,
        m_59_load_reload,
        m_60_load_reload,
        m_61_load_reload,
        m_62_load_reload,
        m_63_load_reload,
        a_3_out,
        a_3_out_ap_vld,
        b_3_out,
        b_3_out_ap_vld,
        c_3_out,
        c_3_out_ap_vld,
        d_1_out,
        d_1_out_ap_vld,
        e_3_out,
        e_3_out_ap_vld,
        f_3_out,
        f_3_out_ap_vld,
        g_3_out,
        g_3_out_ap_vld,
        h_1_out,
        h_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
input  [31:0] b;
input  [31:0] c;
input  [31:0] d;
input  [31:0] e;
input  [31:0] f;
input  [31:0] g;
input  [31:0] h;
input  [31:0] or_ln16_2;
input  [31:0] or_ln16_5;
input  [31:0] or_ln16_8;
input  [31:0] or_ln16_s;
input  [31:0] or_ln16_1;
input  [31:0] or_ln16_3;
input  [31:0] or_ln16_4;
input  [31:0] or_ln16_6;
input  [31:0] or_ln16_7;
input  [31:0] or_ln16_9;
input  [31:0] or_ln16_10;
input  [31:0] or_ln16_11;
input  [31:0] or_ln16_12;
input  [31:0] or_ln16_13;
input  [31:0] or_ln16_14;
input  [31:0] or_ln16_15;
input  [31:0] m_16_load_reload;
input  [31:0] m_17_load_reload;
input  [31:0] m_18_load_reload;
input  [31:0] m_19_load_reload;
input  [31:0] m_20_load_reload;
input  [31:0] m_21_load_reload;
input  [31:0] m_22_load_reload;
input  [31:0] m_23_load_reload;
input  [31:0] m_24_load_reload;
input  [31:0] m_25_load_reload;
input  [31:0] m_26_load_reload;
input  [31:0] m_27_load_reload;
input  [31:0] m_28_load_reload;
input  [31:0] m_29_load_reload;
input  [31:0] m_30_load_reload;
input  [31:0] m_31_load_reload;
input  [31:0] m_32_load_reload;
input  [31:0] m_33_load_reload;
input  [31:0] m_34_load_reload;
input  [31:0] m_35_load_reload;
input  [31:0] m_36_load_reload;
input  [31:0] m_37_load_reload;
input  [31:0] m_38_load_reload;
input  [31:0] m_39_load_reload;
input  [31:0] m_40_load_reload;
input  [31:0] m_41_load_reload;
input  [31:0] m_42_load_reload;
input  [31:0] m_43_load_reload;
input  [31:0] m_44_load_reload;
input  [31:0] m_45_load_reload;
input  [31:0] m_46_load_reload;
input  [31:0] m_47_load_reload;
input  [31:0] m_48_load_reload;
input  [31:0] m_49_load_reload;
input  [31:0] m_50_load_reload;
input  [31:0] m_51_load_reload;
input  [31:0] m_52_load_reload;
input  [31:0] m_53_load_reload;
input  [31:0] m_54_load_reload;
input  [31:0] m_55_load_reload;
input  [31:0] m_56_load_reload;
input  [31:0] m_57_load_reload;
input  [31:0] m_58_load_reload;
input  [31:0] m_59_load_reload;
input  [31:0] m_60_load_reload;
input  [31:0] m_61_load_reload;
input  [31:0] m_62_load_reload;
input  [31:0] m_63_load_reload;
output  [31:0] a_3_out;
output   a_3_out_ap_vld;
output  [31:0] b_3_out;
output   b_3_out_ap_vld;
output  [31:0] c_3_out;
output   c_3_out_ap_vld;
output  [31:0] d_1_out;
output   d_1_out_ap_vld;
output  [31:0] e_3_out;
output   e_3_out_ap_vld;
output  [31:0] f_3_out;
output   f_3_out_ap_vld;
output  [31:0] g_3_out;
output   g_3_out_ap_vld;
output  [31:0] h_1_out;
output   h_1_out_ap_vld;

reg ap_idle;
reg a_3_out_ap_vld;
reg b_3_out_ap_vld;
reg c_3_out_ap_vld;
reg d_1_out_ap_vld;
reg e_3_out_ap_vld;
reg f_3_out_ap_vld;
reg g_3_out_ap_vld;
reg h_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln33_fu_947_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] k_address0;
wire   [31:0] k_q0;
reg   [0:0] icmp_ln33_reg_1625;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] tmp_4_fu_968_p131;
reg   [31:0] tmp_4_reg_1634;
wire   [63:0] zext_ln33_fu_959_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] h_1_fu_362;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [31:0] d_1_fu_366;
reg   [6:0] i_fu_370;
wire   [6:0] add_ln33_fu_953_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [31:0] h_2_fu_374;
reg   [31:0] g_1_fu_378;
reg   [31:0] f_1_fu_382;
wire   [31:0] e_2_fu_1434_p2;
reg   [31:0] d_2_fu_386;
reg   [31:0] c_1_fu_390;
reg   [31:0] b_1_fu_394;
wire   [31:0] a_2_fu_1506_p2;
wire    ap_block_pp0_stage0_01001;
reg    k_ce0_local;
wire   [31:0] tmp_4_fu_968_p129;
wire   [5:0] tmp_4_fu_968_p130;
wire   [5:0] trunc_ln35_fu_1277_p1;
wire   [25:0] lshr_ln1_fu_1267_p4;
wire   [10:0] trunc_ln35_1_fu_1291_p1;
wire   [20:0] lshr_ln35_1_fu_1281_p4;
wire   [31:0] xor_ln35_fu_1309_p2;
wire   [24:0] trunc_ln35_2_fu_1305_p1;
wire   [6:0] lshr_ln35_2_fu_1295_p4;
wire   [31:0] and_ln35_1_fu_1337_p2;
wire   [31:0] and_ln35_fu_1331_p2;
wire   [31:0] or_ln35_1_fu_1323_p3;
wire   [31:0] or_ln35_2_fu_1343_p3;
wire   [31:0] xor_ln35_2_fu_1357_p2;
wire   [31:0] or_ln1_fu_1315_p3;
wire   [31:0] xor_ln35_1_fu_1351_p2;
wire   [31:0] add_ln35_1_fu_1375_p2;
wire   [31:0] xor_ln35_3_fu_1363_p2;
wire   [31:0] add_ln35_2_fu_1380_p2;
wire   [31:0] add_ln35_fu_1369_p2;
wire   [31:0] t1_fu_1386_p2;
wire   [31:0] xor_ln44_fu_1440_p2;
wire   [1:0] trunc_ln36_fu_1402_p1;
wire   [29:0] lshr_ln2_fu_1392_p4;
wire   [12:0] trunc_ln36_1_fu_1416_p1;
wire   [18:0] lshr_ln36_1_fu_1406_p4;
wire   [31:0] and_ln44_fu_1446_p2;
wire   [31:0] and_ln44_1_fu_1452_p2;
wire   [21:0] trunc_ln36_2_fu_1430_p1;
wire   [9:0] lshr_ln36_2_fu_1420_p4;
wire   [31:0] or_ln44_1_fu_1466_p3;
wire   [31:0] or_ln44_2_fu_1480_p3;
wire   [31:0] xor_ln44_2_fu_1488_p2;
wire   [31:0] or_ln2_fu_1458_p3;
wire   [31:0] xor_ln44_3_fu_1494_p2;
wire   [31:0] add_ln44_fu_1500_p2;
wire   [31:0] xor_ln44_1_fu_1474_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] tmp_4_fu_968_p1;
wire   [5:0] tmp_4_fu_968_p3;
wire   [5:0] tmp_4_fu_968_p5;
wire   [5:0] tmp_4_fu_968_p7;
wire   [5:0] tmp_4_fu_968_p9;
wire   [5:0] tmp_4_fu_968_p11;
wire   [5:0] tmp_4_fu_968_p13;
wire   [5:0] tmp_4_fu_968_p15;
wire   [5:0] tmp_4_fu_968_p17;
wire   [5:0] tmp_4_fu_968_p19;
wire   [5:0] tmp_4_fu_968_p21;
wire   [5:0] tmp_4_fu_968_p23;
wire   [5:0] tmp_4_fu_968_p25;
wire   [5:0] tmp_4_fu_968_p27;
wire   [5:0] tmp_4_fu_968_p29;
wire   [5:0] tmp_4_fu_968_p31;
wire   [5:0] tmp_4_fu_968_p33;
wire   [5:0] tmp_4_fu_968_p35;
wire   [5:0] tmp_4_fu_968_p37;
wire   [5:0] tmp_4_fu_968_p39;
wire   [5:0] tmp_4_fu_968_p41;
wire   [5:0] tmp_4_fu_968_p43;
wire   [5:0] tmp_4_fu_968_p45;
wire   [5:0] tmp_4_fu_968_p47;
wire   [5:0] tmp_4_fu_968_p49;
wire   [5:0] tmp_4_fu_968_p51;
wire   [5:0] tmp_4_fu_968_p53;
wire   [5:0] tmp_4_fu_968_p55;
wire   [5:0] tmp_4_fu_968_p57;
wire   [5:0] tmp_4_fu_968_p59;
wire   [5:0] tmp_4_fu_968_p61;
wire   [5:0] tmp_4_fu_968_p63;
wire  signed [5:0] tmp_4_fu_968_p65;
wire  signed [5:0] tmp_4_fu_968_p67;
wire  signed [5:0] tmp_4_fu_968_p69;
wire  signed [5:0] tmp_4_fu_968_p71;
wire  signed [5:0] tmp_4_fu_968_p73;
wire  signed [5:0] tmp_4_fu_968_p75;
wire  signed [5:0] tmp_4_fu_968_p77;
wire  signed [5:0] tmp_4_fu_968_p79;
wire  signed [5:0] tmp_4_fu_968_p81;
wire  signed [5:0] tmp_4_fu_968_p83;
wire  signed [5:0] tmp_4_fu_968_p85;
wire  signed [5:0] tmp_4_fu_968_p87;
wire  signed [5:0] tmp_4_fu_968_p89;
wire  signed [5:0] tmp_4_fu_968_p91;
wire  signed [5:0] tmp_4_fu_968_p93;
wire  signed [5:0] tmp_4_fu_968_p95;
wire  signed [5:0] tmp_4_fu_968_p97;
wire  signed [5:0] tmp_4_fu_968_p99;
wire  signed [5:0] tmp_4_fu_968_p101;
wire  signed [5:0] tmp_4_fu_968_p103;
wire  signed [5:0] tmp_4_fu_968_p105;
wire  signed [5:0] tmp_4_fu_968_p107;
wire  signed [5:0] tmp_4_fu_968_p109;
wire  signed [5:0] tmp_4_fu_968_p111;
wire  signed [5:0] tmp_4_fu_968_p113;
wire  signed [5:0] tmp_4_fu_968_p115;
wire  signed [5:0] tmp_4_fu_968_p117;
wire  signed [5:0] tmp_4_fu_968_p119;
wire  signed [5:0] tmp_4_fu_968_p121;
wire  signed [5:0] tmp_4_fu_968_p123;
wire  signed [5:0] tmp_4_fu_968_p125;
wire  signed [5:0] tmp_4_fu_968_p127;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 h_1_fu_362 = 32'd0;
#0 d_1_fu_366 = 32'd0;
#0 i_fu_370 = 7'd0;
#0 h_2_fu_374 = 32'd0;
#0 g_1_fu_378 = 32'd0;
#0 f_1_fu_382 = 32'd0;
#0 d_2_fu_386 = 32'd0;
#0 c_1_fu_390 = 32'd0;
#0 b_1_fu_394 = 32'd0;
#0 ap_done_reg = 1'b0;
end

sha256_top_sha256_transform_Pipeline_VITIS_LOOP_33_3_k_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
k_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_address0),
    .ce0(k_ce0_local),
    .q0(k_q0)
);

(* dissolve_hierarchy = "yes" *) sha256_top_sparsemux_129_6_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 32 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 32 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 32 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 32 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 32 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 32 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 32 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 32 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 32 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 32 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 32 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 32 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 32 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 32 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 32 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 32 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 32 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 32 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 32 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 32 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 32 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 32 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 32 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 32 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 32 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 32 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 32 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 32 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 32 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 32 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 32 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 32 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sparsemux_129_6_32_1_1_U71(
    .din0(or_ln16_2),
    .din1(or_ln16_5),
    .din2(or_ln16_8),
    .din3(or_ln16_s),
    .din4(or_ln16_1),
    .din5(or_ln16_3),
    .din6(or_ln16_4),
    .din7(or_ln16_6),
    .din8(or_ln16_7),
    .din9(or_ln16_9),
    .din10(or_ln16_10),
    .din11(or_ln16_11),
    .din12(or_ln16_12),
    .din13(or_ln16_13),
    .din14(or_ln16_14),
    .din15(or_ln16_15),
    .din16(m_16_load_reload),
    .din17(m_17_load_reload),
    .din18(m_18_load_reload),
    .din19(m_19_load_reload),
    .din20(m_20_load_reload),
    .din21(m_21_load_reload),
    .din22(m_22_load_reload),
    .din23(m_23_load_reload),
    .din24(m_24_load_reload),
    .din25(m_25_load_reload),
    .din26(m_26_load_reload),
    .din27(m_27_load_reload),
    .din28(m_28_load_reload),
    .din29(m_29_load_reload),
    .din30(m_30_load_reload),
    .din31(m_31_load_reload),
    .din32(m_32_load_reload),
    .din33(m_33_load_reload),
    .din34(m_34_load_reload),
    .din35(m_35_load_reload),
    .din36(m_36_load_reload),
    .din37(m_37_load_reload),
    .din38(m_38_load_reload),
    .din39(m_39_load_reload),
    .din40(m_40_load_reload),
    .din41(m_41_load_reload),
    .din42(m_42_load_reload),
    .din43(m_43_load_reload),
    .din44(m_44_load_reload),
    .din45(m_45_load_reload),
    .din46(m_46_load_reload),
    .din47(m_47_load_reload),
    .din48(m_48_load_reload),
    .din49(m_49_load_reload),
    .din50(m_50_load_reload),
    .din51(m_51_load_reload),
    .din52(m_52_load_reload),
    .din53(m_53_load_reload),
    .din54(m_54_load_reload),
    .din55(m_55_load_reload),
    .din56(m_56_load_reload),
    .din57(m_57_load_reload),
    .din58(m_58_load_reload),
    .din59(m_59_load_reload),
    .din60(m_60_load_reload),
    .din61(m_61_load_reload),
    .din62(m_62_load_reload),
    .din63(m_63_load_reload),
    .def(tmp_4_fu_968_p129),
    .sel(tmp_4_fu_968_p130),
    .dout(tmp_4_fu_968_p131)
);

sha256_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            b_1_fu_394 <= a;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln33_reg_1625 == 1'd0))) begin
            b_1_fu_394 <= a_2_fu_1506_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_1_fu_390 <= b;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln33_reg_1625 == 1'd0))) begin
            c_1_fu_390 <= b_1_fu_394;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            d_1_fu_366 <= d;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln33_reg_1625 == 1'd0))) begin
            d_1_fu_366 <= d_2_fu_386;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            d_2_fu_386 <= c;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln33_reg_1625 == 1'd0))) begin
            d_2_fu_386 <= c_1_fu_390;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            f_1_fu_382 <= e;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln33_reg_1625 == 1'd0))) begin
            f_1_fu_382 <= e_2_fu_1434_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            g_1_fu_378 <= f;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln33_reg_1625 == 1'd0))) begin
            g_1_fu_378 <= f_1_fu_382;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            h_1_fu_362 <= h;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln33_reg_1625 == 1'd0))) begin
            h_1_fu_362 <= h_2_fu_374;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            h_2_fu_374 <= g;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln33_reg_1625 == 1'd0))) begin
            h_2_fu_374 <= g_1_fu_378;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln33_fu_947_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_370 <= add_ln33_fu_953_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_370 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln33_reg_1625 <= icmp_ln33_fu_947_p2;
        tmp_4_reg_1634 <= tmp_4_fu_968_p131;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln33_reg_1625 == 1'd1))) begin
        a_3_out_ap_vld = 1'b1;
    end else begin
        a_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_947_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_370;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln33_reg_1625 == 1'd1))) begin
        b_3_out_ap_vld = 1'b1;
    end else begin
        b_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln33_reg_1625 == 1'd1))) begin
        c_3_out_ap_vld = 1'b1;
    end else begin
        c_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln33_reg_1625 == 1'd1))) begin
        d_1_out_ap_vld = 1'b1;
    end else begin
        d_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln33_reg_1625 == 1'd1))) begin
        e_3_out_ap_vld = 1'b1;
    end else begin
        e_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln33_reg_1625 == 1'd1))) begin
        f_3_out_ap_vld = 1'b1;
    end else begin
        f_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln33_reg_1625 == 1'd1))) begin
        g_3_out_ap_vld = 1'b1;
    end else begin
        g_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln33_reg_1625 == 1'd1))) begin
        h_1_out_ap_vld = 1'b1;
    end else begin
        h_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_ce0_local = 1'b1;
    end else begin
        k_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_2_fu_1506_p2 = (add_ln44_fu_1500_p2 + xor_ln44_1_fu_1474_p2);

assign a_3_out = b_1_fu_394;

assign add_ln33_fu_953_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign add_ln35_1_fu_1375_p2 = (tmp_4_reg_1634 + xor_ln35_1_fu_1351_p2);

assign add_ln35_2_fu_1380_p2 = (add_ln35_1_fu_1375_p2 + xor_ln35_3_fu_1363_p2);

assign add_ln35_fu_1369_p2 = (k_q0 + h_1_fu_362);

assign add_ln44_fu_1500_p2 = (t1_fu_1386_p2 + xor_ln44_3_fu_1494_p2);

assign and_ln35_1_fu_1337_p2 = (xor_ln35_fu_1309_p2 & h_2_fu_374);

assign and_ln35_fu_1331_p2 = (g_1_fu_378 & f_1_fu_382);

assign and_ln44_1_fu_1452_p2 = (d_2_fu_386 & c_1_fu_390);

assign and_ln44_fu_1446_p2 = (xor_ln44_fu_1440_p2 & b_1_fu_394);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_3_out = c_1_fu_390;

assign c_3_out = d_2_fu_386;

assign d_1_out = d_1_fu_366;

assign e_2_fu_1434_p2 = (t1_fu_1386_p2 + d_1_fu_366);

assign e_3_out = f_1_fu_382;

assign f_3_out = g_1_fu_378;

assign g_3_out = h_2_fu_374;

assign h_1_out = h_1_fu_362;

assign icmp_ln33_fu_947_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign k_address0 = zext_ln33_fu_959_p1;

assign lshr_ln1_fu_1267_p4 = {{f_1_fu_382[31:6]}};

assign lshr_ln2_fu_1392_p4 = {{b_1_fu_394[31:2]}};

assign lshr_ln35_1_fu_1281_p4 = {{f_1_fu_382[31:11]}};

assign lshr_ln35_2_fu_1295_p4 = {{f_1_fu_382[31:25]}};

assign lshr_ln36_1_fu_1406_p4 = {{b_1_fu_394[31:13]}};

assign lshr_ln36_2_fu_1420_p4 = {{b_1_fu_394[31:22]}};

assign or_ln1_fu_1315_p3 = {{trunc_ln35_fu_1277_p1}, {lshr_ln1_fu_1267_p4}};

assign or_ln2_fu_1458_p3 = {{trunc_ln36_fu_1402_p1}, {lshr_ln2_fu_1392_p4}};

assign or_ln35_1_fu_1323_p3 = {{trunc_ln35_1_fu_1291_p1}, {lshr_ln35_1_fu_1281_p4}};

assign or_ln35_2_fu_1343_p3 = {{trunc_ln35_2_fu_1305_p1}, {lshr_ln35_2_fu_1295_p4}};

assign or_ln44_1_fu_1466_p3 = {{trunc_ln36_1_fu_1416_p1}, {lshr_ln36_1_fu_1406_p4}};

assign or_ln44_2_fu_1480_p3 = {{trunc_ln36_2_fu_1430_p1}, {lshr_ln36_2_fu_1420_p4}};

assign t1_fu_1386_p2 = (add_ln35_2_fu_1380_p2 + add_ln35_fu_1369_p2);

assign tmp_4_fu_968_p129 = 'bx;

assign tmp_4_fu_968_p130 = ap_sig_allocacmp_i_1[5:0];

assign trunc_ln35_1_fu_1291_p1 = f_1_fu_382[10:0];

assign trunc_ln35_2_fu_1305_p1 = f_1_fu_382[24:0];

assign trunc_ln35_fu_1277_p1 = f_1_fu_382[5:0];

assign trunc_ln36_1_fu_1416_p1 = b_1_fu_394[12:0];

assign trunc_ln36_2_fu_1430_p1 = b_1_fu_394[21:0];

assign trunc_ln36_fu_1402_p1 = b_1_fu_394[1:0];

assign xor_ln35_1_fu_1351_p2 = (and_ln35_fu_1331_p2 ^ and_ln35_1_fu_1337_p2);

assign xor_ln35_2_fu_1357_p2 = (or_ln35_2_fu_1343_p3 ^ or_ln35_1_fu_1323_p3);

assign xor_ln35_3_fu_1363_p2 = (xor_ln35_2_fu_1357_p2 ^ or_ln1_fu_1315_p3);

assign xor_ln35_fu_1309_p2 = (f_1_fu_382 ^ 32'd4294967295);

assign xor_ln44_1_fu_1474_p2 = (and_ln44_fu_1446_p2 ^ and_ln44_1_fu_1452_p2);

assign xor_ln44_2_fu_1488_p2 = (or_ln44_2_fu_1480_p3 ^ or_ln44_1_fu_1466_p3);

assign xor_ln44_3_fu_1494_p2 = (xor_ln44_2_fu_1488_p2 ^ or_ln2_fu_1458_p3);

assign xor_ln44_fu_1440_p2 = (d_2_fu_386 ^ c_1_fu_390);

assign zext_ln33_fu_959_p1 = ap_sig_allocacmp_i_1;

endmodule //sha256_top_sha256_transform_Pipeline_VITIS_LOOP_33_3
