// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sha256_top_sha256_transform (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_address0,
        state_ce0,
        state_we0,
        state_d0,
        state_q0,
        state_address1,
        state_ce1,
        state_we1,
        state_d1,
        state_q1,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        data_32_val,
        data_33_val,
        data_34_val,
        data_35_val,
        data_36_val,
        data_37_val,
        data_38_val,
        data_39_val,
        data_40_val,
        data_41_val,
        data_42_val,
        data_43_val,
        data_44_val,
        data_45_val,
        data_46_val,
        data_47_val,
        data_48_val,
        data_49_val,
        data_50_val,
        data_51_val,
        data_52_val,
        data_53_val,
        data_54_val,
        data_55_val,
        data_56_val,
        data_57_val,
        data_58_val,
        data_59_val,
        data_60_val,
        data_61_val,
        data_62_val,
        data_63_val
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] state_address0;
output   state_ce0;
output   state_we0;
output  [31:0] state_d0;
input  [31:0] state_q0;
output  [2:0] state_address1;
output   state_ce1;
output   state_we1;
output  [31:0] state_d1;
input  [31:0] state_q1;
input  [7:0] data_0_val;
input  [7:0] data_1_val;
input  [7:0] data_2_val;
input  [7:0] data_3_val;
input  [7:0] data_4_val;
input  [7:0] data_5_val;
input  [7:0] data_6_val;
input  [7:0] data_7_val;
input  [7:0] data_8_val;
input  [7:0] data_9_val;
input  [7:0] data_10_val;
input  [7:0] data_11_val;
input  [7:0] data_12_val;
input  [7:0] data_13_val;
input  [7:0] data_14_val;
input  [7:0] data_15_val;
input  [7:0] data_16_val;
input  [7:0] data_17_val;
input  [7:0] data_18_val;
input  [7:0] data_19_val;
input  [7:0] data_20_val;
input  [7:0] data_21_val;
input  [7:0] data_22_val;
input  [7:0] data_23_val;
input  [7:0] data_24_val;
input  [7:0] data_25_val;
input  [7:0] data_26_val;
input  [7:0] data_27_val;
input  [7:0] data_28_val;
input  [7:0] data_29_val;
input  [7:0] data_30_val;
input  [7:0] data_31_val;
input  [7:0] data_32_val;
input  [7:0] data_33_val;
input  [7:0] data_34_val;
input  [7:0] data_35_val;
input  [7:0] data_36_val;
input  [7:0] data_37_val;
input  [7:0] data_38_val;
input  [7:0] data_39_val;
input  [7:0] data_40_val;
input  [7:0] data_41_val;
input  [7:0] data_42_val;
input  [7:0] data_43_val;
input  [7:0] data_44_val;
input  [7:0] data_45_val;
input  [7:0] data_46_val;
input  [7:0] data_47_val;
input  [7:0] data_48_val;
input  [7:0] data_49_val;
input  [7:0] data_50_val;
input  [7:0] data_51_val;
input  [7:0] data_52_val;
input  [7:0] data_53_val;
input  [7:0] data_54_val;
input  [7:0] data_55_val;
input  [7:0] data_56_val;
input  [7:0] data_57_val;
input  [7:0] data_58_val;
input  [7:0] data_59_val;
input  [7:0] data_60_val;
input  [7:0] data_61_val;
input  [7:0] data_62_val;
input  [7:0] data_63_val;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] state_addr_reg_1809;
wire   [2:0] state_addr_1_reg_1814;
reg   [31:0] a_reg_1819;
wire    ap_CS_fsm_state2;
reg   [31:0] b_reg_1825;
wire   [2:0] state_addr_2_reg_1831;
wire   [2:0] state_addr_3_reg_1836;
wire   [31:0] or_ln16_2_fu_1001_p5;
reg   [31:0] or_ln16_2_reg_1841;
wire    ap_CS_fsm_state3;
wire   [31:0] or_ln16_5_fu_1014_p5;
reg   [31:0] or_ln16_5_reg_1847;
wire   [31:0] or_ln16_8_fu_1027_p5;
reg   [31:0] or_ln16_8_reg_1853;
wire   [31:0] or_ln16_s_fu_1040_p5;
reg   [31:0] or_ln16_s_reg_1859;
wire   [31:0] or_ln16_1_fu_1053_p5;
reg   [31:0] or_ln16_1_reg_1865;
wire   [31:0] or_ln16_3_fu_1066_p5;
reg   [31:0] or_ln16_3_reg_1871;
wire   [31:0] or_ln16_4_fu_1079_p5;
reg   [31:0] or_ln16_4_reg_1877;
wire   [31:0] or_ln16_6_fu_1092_p5;
reg   [31:0] or_ln16_6_reg_1883;
wire   [31:0] or_ln16_7_fu_1105_p5;
reg   [31:0] or_ln16_7_reg_1889;
wire   [31:0] or_ln16_9_fu_1118_p5;
reg   [31:0] or_ln16_9_reg_1895;
wire   [31:0] or_ln16_10_fu_1131_p5;
reg   [31:0] or_ln16_10_reg_1901;
wire   [31:0] or_ln16_11_fu_1144_p5;
reg   [31:0] or_ln16_11_reg_1907;
wire   [31:0] or_ln16_12_fu_1157_p5;
reg   [31:0] or_ln16_12_reg_1913;
wire   [31:0] or_ln16_13_fu_1170_p5;
reg   [31:0] or_ln16_13_reg_1919;
wire   [31:0] or_ln16_14_fu_1183_p5;
reg   [31:0] or_ln16_14_reg_1925;
wire   [31:0] or_ln16_15_fu_1196_p5;
reg   [31:0] or_ln16_15_reg_1931;
reg   [31:0] c_reg_1937;
reg   [31:0] d_reg_1943;
wire   [2:0] state_addr_4_reg_1949;
wire   [2:0] state_addr_5_reg_1954;
reg   [31:0] e_reg_1959;
wire    ap_CS_fsm_state4;
reg   [31:0] f_reg_1965;
wire   [2:0] state_addr_6_reg_1971;
wire   [2:0] state_addr_7_reg_1976;
reg   [31:0] g_reg_2125;
wire    ap_CS_fsm_state5;
reg   [31:0] h_reg_2131;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_start;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_done;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_idle;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_ready;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_16_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_16_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_17_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_17_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_18_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_18_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_19_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_19_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_20_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_20_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_21_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_21_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_22_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_22_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_23_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_23_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_24_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_24_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_25_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_25_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_26_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_26_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_27_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_27_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_28_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_28_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_29_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_29_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_30_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_30_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_31_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_31_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_32_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_32_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_33_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_33_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_34_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_34_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_35_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_35_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_36_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_36_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_37_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_37_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_38_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_38_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_39_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_39_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_40_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_40_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_41_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_41_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_42_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_42_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_43_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_43_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_44_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_44_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_45_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_45_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_46_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_46_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_47_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_47_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_48_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_48_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_49_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_49_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_50_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_50_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_51_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_51_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_52_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_52_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_53_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_53_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_54_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_54_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_55_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_55_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_56_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_56_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_57_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_57_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_58_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_58_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_59_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_59_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_60_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_60_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_61_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_61_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_62_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_62_load_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_63_load_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_63_load_out_ap_vld;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_start;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_done;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_idle;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_ready;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_a_3_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_a_3_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_b_3_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_b_3_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_c_3_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_c_3_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_d_1_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_d_1_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_e_3_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_e_3_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_f_3_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_f_3_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_g_3_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_g_3_out_ap_vld;
wire   [31:0] grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_h_1_out;
wire    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_h_1_out_ap_vld;
reg    grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_start_reg;
reg    grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state7;
reg    state_ce1_local;
reg   [2:0] state_address1_local;
reg    state_ce0_local;
reg   [2:0] state_address0_local;
reg    state_we1_local;
reg   [31:0] state_d1_local;
wire   [31:0] add_ln47_fu_1407_p2;
reg    state_we0_local;
reg   [31:0] state_d0_local;
wire   [31:0] add_ln48_fu_1413_p2;
wire   [31:0] add_ln49_fu_1425_p2;
wire   [31:0] add_ln50_fu_1431_p2;
wire   [31:0] add_ln51_fu_1443_p2;
wire   [31:0] add_ln52_fu_1449_p2;
wire   [31:0] add_ln53_fu_1461_p2;
wire   [31:0] add_ln54_fu_1467_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_start_reg = 1'b0;
#0 grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_start_reg = 1'b0;
end

sha256_top_sha256_transform_Pipeline_VITIS_LOOP_19_2 grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_start),
    .ap_done(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_done),
    .ap_idle(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_idle),
    .ap_ready(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_ready),
    .or_ln16_14(or_ln16_14_reg_1925),
    .or_ln16_15(or_ln16_15_reg_1931),
    .or_ln16_9(or_ln16_9_reg_1895),
    .or_ln16_10(or_ln16_10_reg_1901),
    .or_ln16_11(or_ln16_11_reg_1907),
    .or_ln16_12(or_ln16_12_reg_1913),
    .or_ln16_13(or_ln16_13_reg_1919),
    .or_ln16_5(or_ln16_5_reg_1847),
    .or_ln16_8(or_ln16_8_reg_1853),
    .or_ln16_s(or_ln16_s_reg_1859),
    .or_ln16_1(or_ln16_1_reg_1865),
    .or_ln16_3(or_ln16_3_reg_1871),
    .or_ln16_4(or_ln16_4_reg_1877),
    .or_ln16_6(or_ln16_6_reg_1883),
    .or_ln16_7(or_ln16_7_reg_1889),
    .or_ln16_2(or_ln16_2_reg_1841),
    .m_16_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_16_load_out),
    .m_16_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_16_load_out_ap_vld),
    .m_17_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_17_load_out),
    .m_17_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_17_load_out_ap_vld),
    .m_18_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_18_load_out),
    .m_18_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_18_load_out_ap_vld),
    .m_19_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_19_load_out),
    .m_19_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_19_load_out_ap_vld),
    .m_20_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_20_load_out),
    .m_20_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_20_load_out_ap_vld),
    .m_21_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_21_load_out),
    .m_21_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_21_load_out_ap_vld),
    .m_22_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_22_load_out),
    .m_22_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_22_load_out_ap_vld),
    .m_23_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_23_load_out),
    .m_23_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_23_load_out_ap_vld),
    .m_24_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_24_load_out),
    .m_24_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_24_load_out_ap_vld),
    .m_25_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_25_load_out),
    .m_25_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_25_load_out_ap_vld),
    .m_26_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_26_load_out),
    .m_26_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_26_load_out_ap_vld),
    .m_27_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_27_load_out),
    .m_27_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_27_load_out_ap_vld),
    .m_28_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_28_load_out),
    .m_28_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_28_load_out_ap_vld),
    .m_29_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_29_load_out),
    .m_29_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_29_load_out_ap_vld),
    .m_30_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_30_load_out),
    .m_30_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_30_load_out_ap_vld),
    .m_31_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_31_load_out),
    .m_31_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_31_load_out_ap_vld),
    .m_32_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_32_load_out),
    .m_32_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_32_load_out_ap_vld),
    .m_33_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_33_load_out),
    .m_33_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_33_load_out_ap_vld),
    .m_34_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_34_load_out),
    .m_34_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_34_load_out_ap_vld),
    .m_35_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_35_load_out),
    .m_35_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_35_load_out_ap_vld),
    .m_36_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_36_load_out),
    .m_36_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_36_load_out_ap_vld),
    .m_37_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_37_load_out),
    .m_37_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_37_load_out_ap_vld),
    .m_38_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_38_load_out),
    .m_38_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_38_load_out_ap_vld),
    .m_39_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_39_load_out),
    .m_39_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_39_load_out_ap_vld),
    .m_40_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_40_load_out),
    .m_40_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_40_load_out_ap_vld),
    .m_41_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_41_load_out),
    .m_41_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_41_load_out_ap_vld),
    .m_42_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_42_load_out),
    .m_42_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_42_load_out_ap_vld),
    .m_43_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_43_load_out),
    .m_43_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_43_load_out_ap_vld),
    .m_44_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_44_load_out),
    .m_44_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_44_load_out_ap_vld),
    .m_45_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_45_load_out),
    .m_45_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_45_load_out_ap_vld),
    .m_46_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_46_load_out),
    .m_46_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_46_load_out_ap_vld),
    .m_47_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_47_load_out),
    .m_47_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_47_load_out_ap_vld),
    .m_48_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_48_load_out),
    .m_48_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_48_load_out_ap_vld),
    .m_49_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_49_load_out),
    .m_49_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_49_load_out_ap_vld),
    .m_50_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_50_load_out),
    .m_50_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_50_load_out_ap_vld),
    .m_51_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_51_load_out),
    .m_51_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_51_load_out_ap_vld),
    .m_52_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_52_load_out),
    .m_52_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_52_load_out_ap_vld),
    .m_53_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_53_load_out),
    .m_53_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_53_load_out_ap_vld),
    .m_54_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_54_load_out),
    .m_54_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_54_load_out_ap_vld),
    .m_55_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_55_load_out),
    .m_55_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_55_load_out_ap_vld),
    .m_56_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_56_load_out),
    .m_56_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_56_load_out_ap_vld),
    .m_57_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_57_load_out),
    .m_57_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_57_load_out_ap_vld),
    .m_58_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_58_load_out),
    .m_58_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_58_load_out_ap_vld),
    .m_59_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_59_load_out),
    .m_59_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_59_load_out_ap_vld),
    .m_60_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_60_load_out),
    .m_60_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_60_load_out_ap_vld),
    .m_61_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_61_load_out),
    .m_61_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_61_load_out_ap_vld),
    .m_62_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_62_load_out),
    .m_62_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_62_load_out_ap_vld),
    .m_63_load_out(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_63_load_out),
    .m_63_load_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_63_load_out_ap_vld)
);

sha256_top_sha256_transform_Pipeline_VITIS_LOOP_33_3 grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_start),
    .ap_done(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_done),
    .ap_idle(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_idle),
    .ap_ready(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_ready),
    .a(a_reg_1819),
    .b(b_reg_1825),
    .c(c_reg_1937),
    .d(d_reg_1943),
    .e(e_reg_1959),
    .f(f_reg_1965),
    .g(g_reg_2125),
    .h(h_reg_2131),
    .or_ln16_2(or_ln16_2_reg_1841),
    .or_ln16_5(or_ln16_5_reg_1847),
    .or_ln16_8(or_ln16_8_reg_1853),
    .or_ln16_s(or_ln16_s_reg_1859),
    .or_ln16_1(or_ln16_1_reg_1865),
    .or_ln16_3(or_ln16_3_reg_1871),
    .or_ln16_4(or_ln16_4_reg_1877),
    .or_ln16_6(or_ln16_6_reg_1883),
    .or_ln16_7(or_ln16_7_reg_1889),
    .or_ln16_9(or_ln16_9_reg_1895),
    .or_ln16_10(or_ln16_10_reg_1901),
    .or_ln16_11(or_ln16_11_reg_1907),
    .or_ln16_12(or_ln16_12_reg_1913),
    .or_ln16_13(or_ln16_13_reg_1919),
    .or_ln16_14(or_ln16_14_reg_1925),
    .or_ln16_15(or_ln16_15_reg_1931),
    .m_16_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_16_load_out),
    .m_17_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_17_load_out),
    .m_18_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_18_load_out),
    .m_19_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_19_load_out),
    .m_20_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_20_load_out),
    .m_21_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_21_load_out),
    .m_22_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_22_load_out),
    .m_23_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_23_load_out),
    .m_24_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_24_load_out),
    .m_25_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_25_load_out),
    .m_26_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_26_load_out),
    .m_27_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_27_load_out),
    .m_28_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_28_load_out),
    .m_29_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_29_load_out),
    .m_30_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_30_load_out),
    .m_31_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_31_load_out),
    .m_32_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_32_load_out),
    .m_33_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_33_load_out),
    .m_34_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_34_load_out),
    .m_35_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_35_load_out),
    .m_36_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_36_load_out),
    .m_37_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_37_load_out),
    .m_38_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_38_load_out),
    .m_39_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_39_load_out),
    .m_40_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_40_load_out),
    .m_41_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_41_load_out),
    .m_42_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_42_load_out),
    .m_43_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_43_load_out),
    .m_44_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_44_load_out),
    .m_45_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_45_load_out),
    .m_46_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_46_load_out),
    .m_47_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_47_load_out),
    .m_48_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_48_load_out),
    .m_49_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_49_load_out),
    .m_50_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_50_load_out),
    .m_51_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_51_load_out),
    .m_52_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_52_load_out),
    .m_53_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_53_load_out),
    .m_54_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_54_load_out),
    .m_55_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_55_load_out),
    .m_56_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_56_load_out),
    .m_57_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_57_load_out),
    .m_58_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_58_load_out),
    .m_59_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_59_load_out),
    .m_60_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_60_load_out),
    .m_61_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_61_load_out),
    .m_62_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_62_load_out),
    .m_63_load_reload(grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_m_63_load_out),
    .a_3_out(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_a_3_out),
    .a_3_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_a_3_out_ap_vld),
    .b_3_out(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_b_3_out),
    .b_3_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_b_3_out_ap_vld),
    .c_3_out(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_c_3_out),
    .c_3_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_c_3_out_ap_vld),
    .d_1_out(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_d_1_out),
    .d_1_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_d_1_out_ap_vld),
    .e_3_out(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_e_3_out),
    .e_3_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_e_3_out_ap_vld),
    .f_3_out(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_f_3_out),
    .f_3_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_f_3_out_ap_vld),
    .g_3_out(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_g_3_out),
    .g_3_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_g_3_out_ap_vld),
    .h_1_out(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_h_1_out),
    .h_1_out_ap_vld(grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_h_1_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_ready == 1'b1)) begin
            grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_ready == 1'b1)) begin
            grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        a_reg_1819 <= state_q1;
        b_reg_1825 <= state_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        c_reg_1937 <= state_q1;
        d_reg_1943 <= state_q0;
        or_ln16_10_reg_1901 <= or_ln16_10_fu_1131_p5;
        or_ln16_11_reg_1907 <= or_ln16_11_fu_1144_p5;
        or_ln16_12_reg_1913 <= or_ln16_12_fu_1157_p5;
        or_ln16_13_reg_1919 <= or_ln16_13_fu_1170_p5;
        or_ln16_14_reg_1925 <= or_ln16_14_fu_1183_p5;
        or_ln16_15_reg_1931 <= or_ln16_15_fu_1196_p5;
        or_ln16_1_reg_1865 <= or_ln16_1_fu_1053_p5;
        or_ln16_2_reg_1841 <= or_ln16_2_fu_1001_p5;
        or_ln16_3_reg_1871 <= or_ln16_3_fu_1066_p5;
        or_ln16_4_reg_1877 <= or_ln16_4_fu_1079_p5;
        or_ln16_5_reg_1847 <= or_ln16_5_fu_1014_p5;
        or_ln16_6_reg_1883 <= or_ln16_6_fu_1092_p5;
        or_ln16_7_reg_1889 <= or_ln16_7_fu_1105_p5;
        or_ln16_8_reg_1853 <= or_ln16_8_fu_1027_p5;
        or_ln16_9_reg_1895 <= or_ln16_9_fu_1118_p5;
        or_ln16_s_reg_1859 <= or_ln16_s_fu_1040_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        e_reg_1959 <= state_q1;
        f_reg_1965 <= state_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        g_reg_2125 <= state_q1;
        h_reg_2131 <= state_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        state_address0_local = state_addr_7_reg_1976;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        state_address0_local = state_addr_5_reg_1954;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        state_address0_local = state_addr_3_reg_1836;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        state_address0_local = state_addr_1_reg_1814;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        state_address0_local = 64'd1;
    end else begin
        state_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        state_address1_local = state_addr_6_reg_1971;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        state_address1_local = state_addr_4_reg_1949;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        state_address1_local = state_addr_2_reg_1831;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        state_address1_local = state_addr_reg_1809;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        state_address1_local = 64'd0;
    end else begin
        state_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_done == 1'b1)))) begin
        state_ce0_local = 1'b1;
    end else begin
        state_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_done == 1'b1)))) begin
        state_ce1_local = 1'b1;
    end else begin
        state_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        state_d0_local = add_ln54_fu_1467_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        state_d0_local = add_ln52_fu_1449_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        state_d0_local = add_ln50_fu_1431_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        state_d0_local = add_ln48_fu_1413_p2;
    end else begin
        state_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        state_d1_local = add_ln53_fu_1461_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        state_d1_local = add_ln51_fu_1443_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        state_d1_local = add_ln49_fu_1425_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        state_d1_local = add_ln47_fu_1407_p2;
    end else begin
        state_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        state_we0_local = 1'b1;
    end else begin
        state_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        state_we1_local = 1'b1;
    end else begin
        state_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_fu_1407_p2 = (a_reg_1819 + grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_a_3_out);

assign add_ln48_fu_1413_p2 = (b_reg_1825 + grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_b_3_out);

assign add_ln49_fu_1425_p2 = (c_reg_1937 + grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_c_3_out);

assign add_ln50_fu_1431_p2 = (d_reg_1943 + grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_d_1_out);

assign add_ln51_fu_1443_p2 = (e_reg_1959 + grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_e_3_out);

assign add_ln52_fu_1449_p2 = (f_reg_1965 + grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_f_3_out);

assign add_ln53_fu_1461_p2 = (g_reg_2125 + grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_g_3_out);

assign add_ln54_fu_1467_p2 = (h_reg_2131 + grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_h_1_out);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_start = grp_sha256_transform_Pipeline_VITIS_LOOP_19_2_fu_845_ap_start_reg;

assign grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_start = grp_sha256_transform_Pipeline_VITIS_LOOP_33_3_fu_913_ap_start_reg;

assign or_ln16_10_fu_1131_p5 = {{{{data_40_val}, {data_41_val}}, {data_42_val}}, {data_43_val}};

assign or_ln16_11_fu_1144_p5 = {{{{data_44_val}, {data_45_val}}, {data_46_val}}, {data_47_val}};

assign or_ln16_12_fu_1157_p5 = {{{{data_48_val}, {data_49_val}}, {data_50_val}}, {data_51_val}};

assign or_ln16_13_fu_1170_p5 = {{{{data_52_val}, {data_53_val}}, {data_54_val}}, {data_55_val}};

assign or_ln16_14_fu_1183_p5 = {{{{data_56_val}, {data_57_val}}, {data_58_val}}, {data_59_val}};

assign or_ln16_15_fu_1196_p5 = {{{{data_60_val}, {data_61_val}}, {data_62_val}}, {data_63_val}};

assign or_ln16_1_fu_1053_p5 = {{{{data_16_val}, {data_17_val}}, {data_18_val}}, {data_19_val}};

assign or_ln16_2_fu_1001_p5 = {{{{data_0_val}, {data_1_val}}, {data_2_val}}, {data_3_val}};

assign or_ln16_3_fu_1066_p5 = {{{{data_20_val}, {data_21_val}}, {data_22_val}}, {data_23_val}};

assign or_ln16_4_fu_1079_p5 = {{{{data_24_val}, {data_25_val}}, {data_26_val}}, {data_27_val}};

assign or_ln16_5_fu_1014_p5 = {{{{data_4_val}, {data_5_val}}, {data_6_val}}, {data_7_val}};

assign or_ln16_6_fu_1092_p5 = {{{{data_28_val}, {data_29_val}}, {data_30_val}}, {data_31_val}};

assign or_ln16_7_fu_1105_p5 = {{{{data_32_val}, {data_33_val}}, {data_34_val}}, {data_35_val}};

assign or_ln16_8_fu_1027_p5 = {{{{data_8_val}, {data_9_val}}, {data_10_val}}, {data_11_val}};

assign or_ln16_9_fu_1118_p5 = {{{{data_36_val}, {data_37_val}}, {data_38_val}}, {data_39_val}};

assign or_ln16_s_fu_1040_p5 = {{{{data_12_val}, {data_13_val}}, {data_14_val}}, {data_15_val}};

assign state_addr_1_reg_1814 = 64'd1;

assign state_addr_2_reg_1831 = 64'd2;

assign state_addr_3_reg_1836 = 64'd3;

assign state_addr_4_reg_1949 = 64'd4;

assign state_addr_5_reg_1954 = 64'd5;

assign state_addr_6_reg_1971 = 64'd6;

assign state_addr_7_reg_1976 = 64'd7;

assign state_addr_reg_1809 = 64'd0;

assign state_address0 = state_address0_local;

assign state_address1 = state_address1_local;

assign state_ce0 = state_ce0_local;

assign state_ce1 = state_ce1_local;

assign state_d0 = state_d0_local;

assign state_d1 = state_d1_local;

assign state_we0 = state_we0_local;

assign state_we1 = state_we1_local;

endmodule //sha256_top_sha256_transform
