
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsha256_top.h"

/*
* The configuration table for devices
*/

XSha256_top_Config XSha256_top_ConfigTable[XPAR_XSHA256_TOP_NUM_INSTANCES] =
{
	{
		XPAR_SHA256_TOP_0_DEVICE_ID,
		XPAR_SHA256_TOP_0_S_AXI_CONTROL_BASEADDR
	}
};


